<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title><?= $this->e($title) ?></title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <base href="<?= $this->e($base) ?>">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
    <?= $this->section('content') ?>
</body>

</html>
